language: java

matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk11
    - jdk: openjdk15

    - os: osx
      osx_image: xcode10.2
      env: JAVA_HOME=$(/usr/libexec/java_home)

cache:
  directories:
  - $HOME/.m2
