name: Build and Test
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17]
        os: [ubuntu-22.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.Java }} Build and Test (${{ matrix.os }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: ${{ matrix.java }}
      - name: Maven verify
        run: mvn -V -B verify
